<#
.SYNOPSIS
    Pre-commit checks for code quality and security.
.DESCRIPTION
    This script runs various checks. Security and syntax checks (private keys, merge conflicts, YAML parser)
    run on staged Git blobs, while style checks (line endings, trailing whitespace) run on local workspace files.
#>

$ErrorActionPreference = "Stop"

Write-Host "Running pre-commit quality and security checks..." -ForegroundColor Cyan

# Helper function to validate YAML syntax using the real YamlDotNet parser
function Test-YamlSyntax {
    param(
        [string]$Filepath,
        [string]$Filename
    )

    # Search for YamlDotNet DLL generated by the tests build
    $dllSearchPaths = @(
        "winui3/SquirrelNotifier.WinUI3.Tests/bin/Release/net10.0-windows10.0.26100.0/win-x64/YamlDotNet.dll",
        "winui3/SquirrelNotifier.WinUI3.Tests/bin/Debug/net10.0-windows10.0.26100.0/win-x64/YamlDotNet.dll"
    )
    $yamlDotNetDll = $null
    foreach ($path in $dllSearchPaths) {
        if (Test-Path $path) {
            $yamlDotNetDll = (Resolve-Path $path).Path
            break
        }
    }

    if ($null -eq $yamlDotNetDll) {
        Write-Host "ERROR: YamlDotNet.dll is missing! Please build the solution first: dotnet build winui3\SquirrelNotifier.WinUI3.sln" -ForegroundColor Red
        return $false
    }

    try {
        # Load YamlDotNet assembly into the PowerShell session
        Add-Type -Path $yamlDotNetDll
    } catch {
        Write-Host "ERROR: Failed to load YamlDotNet assembly: $_" -ForegroundColor Red
        return $false
    }

    $reader = $null
    try {
        $reader = [System.IO.StreamReader]::new($Filepath)
        $deserializer = [YamlDotNet.Serialization.DeserializerBuilder]::new().Build()

        # Parse YAML structure. Exceptions will be thrown on any syntax/semantic errors
        $deserializer.Deserialize($reader) | Out-Null

        return $true
    } catch {
        Write-Host "ERROR: YAML syntax error in staged '$Filename':" -ForegroundColor Red
        Write-Host $_.Exception.Message -ForegroundColor Yellow
        return $false
    } finally {
        if ($null -ne $reader) {
            $reader.Close()
        }
    }
}

# Get staged files
$stagedFiles = git diff --cached --name-only --diff-filter=ACM
if ($null -eq $stagedFiles -or $stagedFiles.Count -eq 0) {
    Write-Host "No staged files to check." -ForegroundColor Green
    exit 0
}

$binaryExtensions = @(".png", ".jpg", ".jpeg", ".gif", ".ico", ".zip", ".pdf", ".dll", ".exe")
$failed = $false

# A. Case conflict check
$lowercasePaths = @{}
foreach ($file in $stagedFiles) {
    $lower = $file.ToLowerInvariant()
    if ($lowercasePaths.ContainsKey($lower)) {
        Write-Host "ERROR: Case conflict detected between '$file' and '$($lowercasePaths[$lower])'" -ForegroundColor Red
        $failed = $true
    }
    $lowercasePaths[$lower] = $file
}

# B. Checks per file
foreach ($file in $stagedFiles) {
    $gitFilePath = $file.Replace('\', '/')
    $ext = [System.IO.Path]::GetExtension($file).ToLowerInvariant()

    # Fetch staged content size
    $sizeStr = (git cat-file -s ":$gitFilePath" 2>$null)
    if ($LASTEXITCODE -ne 0) {
        continue
    }
    $size = [int64]$sizeStr

    # --- PART 1: Staged Blob Security & Integrity Checks ---
    $tempFile = [System.IO.Path]::GetTempFileName()
    try {
        # Export staged blob to temporary file
        cmd.exe /c "git show :`"$gitFilePath`" > `"$tempFile`""

        # Large files check (max 1000KB)
        if ($size -gt 1000 * 1024) {
            Write-Host "ERROR: Staged content for '$file' is too large ($([Math]::Round($size / 1024, 2)) KB). Max allowed size is 1000 KB." -ForegroundColor Red
            $failed = $true
        }

        if (-not ($binaryExtensions -contains $ext)) {
            $rawBytes = [System.IO.File]::ReadAllBytes($tempFile)
            if ($rawBytes.Length -gt 0) {
                $content = [System.Text.Encoding]::UTF8.GetString($rawBytes)

                # Merge conflict marker check
                if ($content -match '(?m)^(<<<<<<<|=======|>>>>>>>)(?:\s|$)') {
                    Write-Host "ERROR: Merge conflict marker found in staged '$file'." -ForegroundColor Red
                    $failed = $true
                }

                # Private key check
                if ($content -match '-----BEGIN[ A-Z0-9_-]+PRIVATE KEY-----') {
                    Write-Host "ERROR: Potential private key detected in staged '$file'!" -ForegroundColor Red
                    $failed = $true
                }

                # YAML syntax validation using real YamlDotNet parser
                if ($ext -eq ".yml" -or $ext -eq ".yaml") {
                    if (-not (Test-YamlSyntax -Filepath $tempFile -Filename $file)) {
                        $failed = $true
                    }
                }
            }
        }
    } finally {
        if (Test-Path $tempFile) {
            Remove-Item $tempFile -Force
        }
    }

    # --- PART 2: Local Workspace File Style & Quality Checks ---
    # Only run style checks if the file physically exists in the workspace
    if (Test-Path $file) {
        if ($binaryExtensions -contains $ext) { continue }

        $rawBytes = [System.IO.File]::ReadAllBytes((Resolve-Path $file).Path)
        if ($rawBytes.Length -eq 0) { continue }

        # Line endings check (CRLF unified)
        $hasLFWithoutCR = $false
        for ($i = 0; $i -lt $rawBytes.Length; $i++) {
            if ($rawBytes[$i] -eq 10) { # LF (\n)
                if ($i -eq 0 -or $rawBytes[$i-1] -ne 13) { # Not CR (\r)
                    $hasLFWithoutCR = $true
                    break
                }
            }
        }
        if ($hasLFWithoutCR) {
            Write-Host "ERROR: Non-CRLF (LF-only) line endings detected in '$file'. Only CRLF is allowed." -ForegroundColor Red
            $failed = $true
        }

        # End of file newline check
        if ($ext -ne ".svg") {
            $lastByte = $rawBytes[$rawBytes.Length - 1]
            if ($lastByte -ne 10) {
                Write-Host "ERROR: File '$file' does not end with a newline." -ForegroundColor Red
                $failed = $true
            }
        }

        # Trailing whitespace check (exclude markdown files)
        $lines = [System.IO.File]::ReadAllLines((Resolve-Path $file).Path, [System.Text.Encoding]::UTF8)
        if ($ext -ne ".md") {
            $lineNum = 1
            foreach ($line in $lines) {
                if ($line -match '\s+$') {
                    Write-Host "ERROR: Trailing whitespace found in '$file' at line $lineNum." -ForegroundColor Red
                    $failed = $true
                    break
                }
                $lineNum++
            }
        }
    }
}

if ($failed) {
    Write-Host ""
    Write-Host "Pre-commit checks failed! Please resolve the errors above." -ForegroundColor Red
    exit 1
}

Write-Host "✓ All pre-commit quality and security checks passed" -ForegroundColor Green
exit 0
